version: '3.8'
services:
  companies:
    build: 
      args: 
        user: admin
        uid: 1000
      context: ./
      dockerfile: dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes: 
      - ./:/var/www
    networks:
      - microservices

  companies_nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports: 
      - 8000:80
      - 443:443
    volumes: 
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - microservices

  companies_db:
    image: mariadb:10.5
    restart: unless-stopped 
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./.docker/database:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
