version: '3.8'
services:
    system_db:
        container_name: system_db
        image: mariadb:10.5
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/database:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - microservices

networks:
  microservices:
    driver: bridge

